### ISSUE TITLE
How to Create Artifactory OSS on openshift

### ISSUE THREAD

**Issue by iberodev** [goern/artifactory-on-openshift#2]
I found this repository when looking for a way to create Artifactory OSS in OpenShift.

I am new to OpenShift so I'm not sure whether I am doing anything wrong.
I have minishift up and running locally.

I created a project called artifactory-project

Then I import the https://github.com/goern/artifactory-on-openshift/blob/master/artifactory.yaml

and I follow the 3 steps wizard to create it. At the last step it fails to create with the following errors:

> Cannot create image stream "artifactory". ImageStream "artifactory" is invalid: spec.tags[5.2.1].from.name: Forbidden: registry "docker.bintray.io" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 5 more ...

Isn't this the way this is supposed to be used? Is it due to the template being outdated?
Any advice, guide on how to have Artifactory OSS on minishift would be much appreciated if this is not an issue.

Thank you!

**Comment by goern** [comment]
It's an OpenShift configuration issue, the bintray registry is not allowed. Are you running minishift or what version?

**Comment by iberodev** [comment]
I'm running minishift enterprise (the one from RedHat, not the community edition)
About

```
Version
OpenShift Master:
v3.9.31
Kubernetes Master:
v1.9.1+a0ce1bc657
OpenShift Web Console:
v3.9.31
```

**Comment by goern** [comment]
ja, that has a limited set of whitelisted registries. read up on the docs how to extend that list.

**Comment by iberodev** [comment]
thank you. So the process would be just as I did as soon as I extend the list and then I would have a pod with artifactory oss in it?

**Comment by goern** [comment]
I think so :)

**Comment by devops-42** [comment]
Same problem with installation of Xray-OSS: I added docker.bintray.io as insecure registry and validated it by:

```
$ minishift config get insecure-registry
[docker.bintray.io:443]
```

Nevertheless the error occurs:

`Error from server (Invalid): ImageStream "rabbitmq" is invalid: spec.tags[latest].from.name: Forbidden: registry "docker.bintray.io" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443", and 5 more ...`

Any solutions?

Cheers

**Comment by goern** [comment]
Just the same advise as described above :/

**Comment by devops-42** [comment]
Hi @goern ,

meanwhile I found a command by means of which I'm able to patch the Minishift config without rebooting. It's working now. Thanks for your advise.

Cheers
